# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
# eventstore
  - package-ecosystem: "gomod"
    directory: "/eventstore/esdb/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/eventstore/bbolt/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod" 
    directory: "/eventstore/sql/" 
    schedule:
      interval: "weekly"
# snapshotstore
  - package-ecosystem: "gomod"
    directory: "/snapshotstore/sql/"
    schedule:
      interval: "weekly"
