language: go

go:
- 1.16.x

jobs:
  include:
    - stage: build
      script:
        - go get ./...
        - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
        - cd eventstore/bbolt
        - go get ./...
        - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
        - cd ../sql
        - go get ./...
        - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        skip_cleanup: true
        on:
          # Creates a new deployment when a tag is pushed to master
          branch: master
          tags: true

